export const productsData = [
    {
      id : 1,
      title: "Just In",
      name: "Nike Air Force 1 Mid '07",
      text : "Men's Shoes",
      colors : "1 Colour",
      price: "MRP : ₹ 2 495.00",
      detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
      image: "/images/product1.png",
    },
    {
        id : 2,
        title: "Just In",
        name: "Nike Court Vision Low Next Nature",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 4 995.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product2.png",
      },
      {
        id : 3,
        title: "Just In",
        name: "Nike Air Force 1 PLT.AF.ORM",
        text : "Women's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 8 695.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product3.png",
      },
      {
        id : 4,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product4.png",
      },
      {
        id : 5,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product5.png",
      },
      {
        id : 6,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product6.png",
      },{
        id : 7,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product7.png",
      },{
        id : 8,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product8.png",
      },{
        id : 9,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product9.png",
      },{
        id : 10,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product10.png",
      },{
        id : 11,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product11.png",
      },{
        id : 12,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product12.png",
      },{
        id : 13,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product13.png",
      },{
        id : 14,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product14.png",
      },{
        id : 15,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product15.png",
      },{
        id : 16,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product16.png",
      },{
        id : 17,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product17.png",
      },{
        id : 18,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product18.png",
      },{
        id : 19,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product19.png",
      },{
        id : 20,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product20.png",
      },{
        id : 21,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product21.png",
      },{
        id : 22,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product22.png",
      },{
        id : 23,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product23.png",
      },{
        id : 24,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product24.png",
      },{
        id : 25,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/Image4.png",
      },{
        id : 26,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product26.png",
      },{
        id : 27,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product27.png",
      },{
        id : 28,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product28.png",
      },
      {
        id : 29,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product29.png",
      },
      {
        id : 30,
        title: "Just In",
        name: "Nike Air Force 1 React",
        text : "Men's Shoes",
        colors : "1 Colour",
        price: "MRP : ₹ 13 295.00",
        detail : "Turn style on its head with this crafted take on the Air Jordan 1 Mid. Its inside out-inspired construction, including unique layering and exposed foam accents, ups the ante on this timeless Jordan Brand silhouette. Details like the deco stitching on the Swoosh add coveted appeal, while the unexpected shading, rich mixture of materials and aged midsole aesthetic give this release an artisan finish.",
        image: "/images/product30.png",
      }
  ];